# https://taskfile.dev

version: '3'

env:
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org,direct

vars:
  DOCKER: '{{default "docker" .DOCKER}}'

tasks:
  setup:
    desc: Install dependencies
    cmds:
      - go mod tidy

  cover:
    desc: Open the cover tool
    cmds:
      - go tool cover -html=coverage.txt

  fmt:
    desc: gofumpt all code
    cmds:
      - gofumpt -w -l .

  lint:
    desc: Lint the code with golangci-lint
    cmds:
      - task: fmt
      - golangci-lint run ./...

  docs:serve:
    dir: www
    desc: Start local documentation server
    cmds:
      - yarn run start

  goreleaser:snapshot:
    desc: Run GoReleaser in snapshot mode
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist

  # Example: task release -- v0.0.2-dev
  release:
    desc: Create git tag and release via GitHub Action
    cmds:
      - git tag {{.CLI_ARGS}}
      - git push --tags