# Dockerfile
{{- if(eq .Image "Alpine")}}
FROM alpine:3.15
LABEL maintainer "svx <sven@so36.net>"
LABEL description=""
# hadolint ignore=DL3018
RUN addgroup -S svx && adduser -D -S svx svx
USER svx
{{else if eq .Image "Debian"}}
FROM debian:11
LABEL maintainer "svx <sven@so36.net>"
LABEL description=""
# hadolint ignore=DL3008
RUN addgroup -S svx && adduser -D -S svx svx
USER svx
{{else if eq .Image "Node"}}
# ---- Base Node ----
FROM node:16-alpine3.15 as base
LABEL maintainer "svx <sven@so36.net>"
LABEL description=""

# hadolint ignore=DL3018
RUN apk --no-cache add git \

USER node
WORKDIR /app/website
{{- end }}